#!/usr/bin/env node

/**
 * First-time Project Setup
 *
 * Interactive setup for new developers
 *
 * Usage:
 *   npm run dev:setup
 */

const fs = require('fs-extra')
const path = require('path')
const { execSync } = require('child_process')
const chalk = require('chalk')
const inquirer = require('inquirer')

// Project root
const PROJECT_ROOT = path.resolve(__dirname, '../..')

/**
 * Main setup
 */
async function main() {
  try {
    console.log(chalk.blue.bold('\n🚀 Project Setup\n'))
    console.log(chalk.gray('This wizard will help you set up the project for development.\n'))

    // Check prerequisites
    await checkPrerequisites()

    // Install dependencies
    await installDependencies()

    // Setup environment
    await setupEnvironment()

    // Setup Git hooks
    await setupGitHooks()

    // Optional: Setup Supabase
    const setupSupabase = await promptSetupSupabase()
    if (setupSupabase) {
      await setupSupabaseLocal()
    }

    // Run doctor
    await runDoctor()

    // Success
    console.log(chalk.green.bold('\n✅ Setup complete!\n'))
    showNextSteps()
  } catch (error) {
    console.error(chalk.red('❌ Setup failed:'), error.message)
    process.exit(1)
  }
}

/**
 * Check prerequisites
 */
async function checkPrerequisites() {
  console.log(chalk.blue('Checking prerequisites...\n'))

  const checks = [
    { name: 'Node.js', command: 'node --version', minVersion: 20 },
    { name: 'npm', command: 'npm --version', minVersion: 10 },
    { name: 'Git', command: 'git --version', minVersion: 2 },
  ]

  for (const check of checks) {
    try {
      const version = execSync(check.command, { encoding: 'utf-8' }).trim()
      console.log(chalk.green(`  ✓ ${check.name}: ${version}`))
    } catch (error) {
      console.log(chalk.red(`  ✗ ${check.name} not found`))
      throw new Error(`${check.name} is required but not installed`)
    }
  }

  console.log()
}

/**
 * Install dependencies
 */
async function installDependencies() {
  console.log(chalk.blue('Installing dependencies...\n'))

  const nodeModulesPath = path.join(PROJECT_ROOT, 'node_modules')

  if (await fs.pathExists(nodeModulesPath)) {
    const answer = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'reinstall',
        message: 'Dependencies already installed. Reinstall?',
        default: false,
      },
    ])

    if (!answer.reinstall) {
      console.log(chalk.gray('  Skipping dependency installation\n'))
      return
    }
  }

  try {
    console.log(chalk.gray('  Running npm install...\n'))
    execSync('npm install', { cwd: PROJECT_ROOT, stdio: 'inherit' })
    console.log(chalk.green('\n  ✓ Dependencies installed\n'))
  } catch (error) {
    throw new Error('Failed to install dependencies')
  }
}

/**
 * Setup environment
 */
async function setupEnvironment() {
  console.log(chalk.blue('Setting up environment...\n'))

  const envPath = path.join(PROJECT_ROOT, '.env.local')
  const envExamplePath = path.join(PROJECT_ROOT, '.env.example')

  if (await fs.pathExists(envPath)) {
    const answer = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'overwrite',
        message: '.env.local already exists. Overwrite?',
        default: false,
      },
    ])

    if (!answer.overwrite) {
      console.log(chalk.gray('  Keeping existing .env.local\n'))
      return
    }
  }

  // Prompt for environment variables
  const answers = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'useSupabase',
      message: 'Will you use Supabase?',
      default: true,
    },
    {
      type: 'input',
      name: 'supabaseUrl',
      message: 'Supabase URL (or press Enter to use local):',
      default: 'http://localhost:54321',
      when: (answers) => answers.useSupabase,
    },
    {
      type: 'input',
      name: 'supabaseAnonKey',
      message: 'Supabase Anon Key (or press Enter to skip):',
      when: (answers) => answers.useSupabase,
    },
  ])

  // Create .env.local
  let envContent = '# Environment Variables\n'
  envContent += '# Generated by setup wizard\n\n'

  if (answers.useSupabase) {
    envContent += '# Supabase\n'
    envContent += `SUPABASE_URL=${answers.supabaseUrl}\n`
    envContent += `SUPABASE_ANON_KEY=${answers.supabaseAnonKey || 'your-anon-key'}\n`
    envContent += 'SUPABASE_SECRET_KEY=your-service-role-key\n'
    envContent += 'SUPABASE_PROJECT_ID=your-project-id\n'
  }

  await fs.writeFile(envPath, envContent)
  console.log(chalk.green('  ✓ .env.local created\n'))
}

/**
 * Setup Git hooks
 */
async function setupGitHooks() {
  console.log(chalk.blue('Setting up Git hooks...\n'))

  try {
    execSync('npx husky install', { cwd: PROJECT_ROOT, stdio: 'pipe' })
    console.log(chalk.green('  ✓ Git hooks installed\n'))
  } catch (error) {
    console.log(chalk.yellow('  ⚠️  Failed to setup Git hooks (non-critical)\n'))
  }
}

/**
 * Prompt to setup Supabase
 */
async function promptSetupSupabase() {
  const answer = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'setup',
      message: 'Setup local Supabase? (Requires Docker)',
      default: false,
    },
  ])

  return answer.setup
}

/**
 * Setup local Supabase
 */
async function setupSupabaseLocal() {
  console.log(chalk.blue('Setting up local Supabase...\n'))

  try {
    // Check if Supabase CLI is installed
    execSync('supabase --version', { stdio: 'ignore' })
  } catch (error) {
    console.log(chalk.yellow('  ⚠️  Supabase CLI not found\n'))
    console.log(chalk.gray('  Install with: npm install -g supabase\n'))
    return
  }

  try {
    // Check if Supabase is initialized
    const supabaseDir = path.join(PROJECT_ROOT, 'supabase')
    if (!await fs.pathExists(supabaseDir)) {
      console.log(chalk.gray('  Initializing Supabase...\n'))
      execSync('supabase init', { cwd: PROJECT_ROOT, stdio: 'inherit' })
    }

    // Start Supabase
    console.log(chalk.gray('  Starting Supabase...\n'))
    execSync('supabase start', { cwd: PROJECT_ROOT, stdio: 'inherit' })

    console.log(chalk.green('\n  ✓ Supabase started\n'))
  } catch (error) {
    console.log(chalk.yellow('  ⚠️  Failed to setup Supabase\n'))
    console.log(chalk.gray('  You can set it up manually later\n'))
  }
}

/**
 * Run doctor
 */
async function runDoctor() {
  console.log(chalk.blue('Running environment check...\n'))

  const answer = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'run',
      message: 'Run environment diagnostics?',
      default: true,
    },
  ])

  if (answer.run) {
    try {
      execSync('node scripts/dev/doctor.js', {
        cwd: PROJECT_ROOT,
        stdio: 'inherit',
      })
    } catch (error) {
      // Doctor will handle its own errors
    }
  }
}

/**
 * Show next steps
 */
function showNextSteps() {
  console.log(chalk.blue.bold('📋 Next Steps:\n'))
  console.log(chalk.gray('1. Start development server:'))
  console.log(chalk.cyan('   npm start\n'))
  console.log(chalk.gray('2. Open in simulator:'))
  console.log(chalk.cyan('   npm run ios'))
  console.log(chalk.cyan('   npm run android\n'))
  console.log(chalk.gray('3. Run tests:'))
  console.log(chalk.cyan('   npm test\n'))
  console.log(chalk.gray('4. Generate a component:'))
  console.log(chalk.cyan('   npm run generate component Button\n'))
  console.log(chalk.gray('5. Read the docs:'))
  console.log(chalk.cyan('   docs/00-getting-started/QUICKSTART.md\n'))
}

// Run setup
main()
