/**
 * Styles for Metrics Dashboard Components
 */

import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  scrollView: { flex: 1 },
  scrollContent: { padding: 16 },
  header: { marginBottom: 20 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#333', marginBottom: 4 },
  subtitle: { fontSize: 14, color: '#666' },
  periodSelector: { flexDirection: 'row', gap: 8, marginBottom: 20 },
  periodButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    alignItems: 'center',
  },
  periodButtonActive: { backgroundColor: '#2196F3', borderColor: '#2196F3' },
  periodButtonText: { fontSize: 14, fontWeight: '600', color: '#666' },
  periodButtonTextActive: { color: '#fff' },
  metricsGrid: { gap: 12, marginBottom: 24 },
  metricCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  metricCardSelected: { borderColor: '#2196F3' },
  metricLabel: { fontSize: 14, fontWeight: '600', color: '#666', marginBottom: 8 },
  metricValue: { fontSize: 32, fontWeight: 'bold', color: '#333', marginBottom: 12 },
  metricUnit: { fontSize: 16, fontWeight: 'normal', color: '#999' },
  metricStats: { flexDirection: 'row', gap: 16 },
  metricStat: { flex: 1 },
  metricStatLabel: { fontSize: 11, color: '#999', marginBottom: 2 },
  metricStatValue: { fontSize: 16, fontWeight: '600', color: '#333' },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 12 },
  detailsSection: { marginBottom: 24 },
  detailsCard: { backgroundColor: '#fff', borderRadius: 12, padding: 16 },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  detailLabel: { fontSize: 14, color: '#666' },
  detailValue: { fontSize: 14, fontWeight: '600', color: '#333' },
  groupedList: { backgroundColor: '#fff', borderRadius: 12, overflow: 'hidden' },
  groupedItem: { padding: 16, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  groupedKey: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 8 },
  groupedStats: { flexDirection: 'row', gap: 16 },
  groupedStat: { flex: 1 },
  groupedStatLabel: { fontSize: 11, color: '#999', marginBottom: 2 },
  groupedStatValue: { fontSize: 14, fontWeight: '600', color: '#666' },
  loading: { padding: 40, alignItems: 'center', justifyContent: 'center' },
  emptyState: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
  },
  emptyStateText: { fontSize: 14, color: '#999' },
});
